module.exports = {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.jsx',
        './resources/**/*.ts',
        './resources/**/*.tsx',
    ],
    theme: {
        extend: {
            colors: {
                'primary': '#3525cd',
                'on-primary': '#ffffff',
                'primary-container': '#4f46e5',
                'on-primary-container': '#dad7ff',
                'primary-fixed': '#e2dfff',
                'primary-fixed-dim': '#c3c0ff',
                'on-primary-fixed': '#0f0069',
                'on-primary-fixed-variant': '#3323cc',
                'secondary': '#006c49',
                'on-secondary': '#ffffff',
                'secondary-container': '#6cf8bb',
                'on-secondary-container': '#00714d',
                'secondary-fixed': '#6ffbbe',
                'secondary-fixed-dim': '#4edea3',
                'on-secondary-fixed': '#002113',
                'on-secondary-fixed-variant': '#005236',
                'tertiary': '#7e3000',
                'on-tertiary': '#ffffff',
                'tertiary-container': '#a44100',
                'on-tertiary-container': '#ffd2be',
                'tertiary-fixed': '#ffdbcc',
                'tertiary-fixed-dim': '#ffb695',
                'on-tertiary-fixed': '#351000',
                'on-tertiary-fixed-variant': '#7b2f00',
                'error': '#ba1a1a',
                'on-error': '#ffffff',
                'error-container': '#ffdad6',
                'on-error-container': '#93000a',
                'background': '#faf8ff',
                'on-background': '#131b2e',
                'surface': '#faf8ff',
                'on-surface': '#131b2e',
                'surface-variant': '#dae2fd',
                'on-surface-variant': '#464555',
                'outline': '#777587',
                'outline-variant': '#c7c4d8',
                'surface-dim': '#d2d9f4',
                'surface-bright': '#faf8ff',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#f2f3ff',
                'surface-container': '#eaedff',
                'surface-container-high': '#e2e7ff',
                'surface-container-highest': '#dae2fd',
                'inverse-surface': '#283044',
                'inverse-on-surface': '#eef0ff',
                'inverse-primary': '#c3c0ff',
                'surface-tint': '#4d44e3',
            },
            fontFamily: {
                'body-md': ['Inter'],
                'body-sm': ['Inter'],
                'body-lg': ['Inter'],
                'headline-lg': ['Geist'],
                'headline-md': ['Geist'],
                'headline-sm': ['Geist'],
                'label-md': ['Geist'],
                'mono-data': ['Geist'],
                'display-lg': ['Geist'],
            },
            borderRadius: {
                'DEFAULT': '0.25rem',
                'lg': '0.5rem',
                'xl': '0.75rem',
                'full': '9999px',
            },
        },
    },
    plugins: [],
};
